---
author: "Jan Paul van Meenen"
---

Here data from 01_a_Manaus_Data is prepared for usage in stan

#Manaus 
## Packages 

```{r}
#data management 
data_management_packages_to_install <- c("data.table", "tidyverse", "readxl", "yarrr", "ggplot2", "zoo", "ggdist", "ggbeeswarm", "GGally", "posterior", "bayesplot", "tidyverse")

packages_to_install <- c(data_management_packages_to_install)

# Check and install packages using a for loop
for (package in packages_to_install) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
  library(package, character.only = TRUE)
}
cmdstanr::register_knitr_engine(override = FALSE)
```

# Converting data 
## general
### Prelimenaries
```{r}
J <- 2 #number of infectious compartments
K <- 2 #number of recovered compartments
numberofageclasses <- 8

#ODE integrator arguments
rel_tol <- 1e-5 
abs_tol <- 1e-7
max_num_steps <- 1e6
```

### Dates & time 
```{r}
dateofffirstcase <- date("2020-03-13") 
dateoffirstconfirmeddeath <- date("2020-03-27")
dateoffirstsero <- date("2020-03-10")

end_date_1 <- date("2020-08-01") #wave 1
end_date <- date("2021-05-01") #wave 2 included

set_start_date <- dateoffirstsero - 10 #"2020-02-29"
set_end_date <- end_date  

numdays_all <- as.numeric(set_end_date - set_start_date)
ts_all <- 1:numdays_all

dateoffirstconfirmeddeath - set_start_date #between first death and first mobility data date
dateoffirstconfirmeddeath - date("2020-01-01") #between first case and beginning of year

phylogenetic_t1_median_date <- as.Date("2020-11-15")
phylogenetic_t1_timepoint_median <- as.numeric(phylogenetic_t1_median_date - set_start_date)
phylogenetic_t1_timepoint_interval_95p <- as.numeric(as.Date("2020-11-24") - as.Date("2020-10-06"))
phylogenetic_t1_timepoint_interval_sd <- phylogenetic_t1_timepoint_interval_95p / (2*1.96)
```

### Hospital deaths 
```{r}
hospitaldeaths_selected <- data_hospdeaths_wide %>%
  filter(DT_EVOLUTION > set_start_date,
         DT_EVOLUTION <= set_end_date) %>%
  mutate(time = as.numeric(DT_EVOLUTION - set_start_date)) %>%
  select(-c(DT_EVOLUTION)) %>%
  column_to_rownames(var = "time") %>%
  as.matrix()

numdays_hospdeaths <- dim(hospitaldeaths_selected)[1]
numdays_hospdeaths

head(hospitaldeaths_selected, numdays_hospdeaths)
tail(hospitaldeaths_selected, 100)

hospitaldeaths_times <- data_hospdeaths_wide %>%
  filter(DT_EVOLUTION > set_start_date,
         DT_EVOLUTION <= set_end_date) %>%
  mutate(time = as.numeric(DT_EVOLUTION - set_start_date)) %>%
  distinct(time) 
```

### Seroprevalence
```{r}
sero_num_sampled <- data_serosamples_wide %>%
  filter(date <= set_end_date) %>%
  mutate(time = as.numeric(date - set_start_date)) %>%
  select(!date) %>%
  column_to_rownames(var = "time") %>%
  as.matrix()

sero_num_sampled

sero_num_pos_140 <- data_seropos_140_wide %>%
  filter(date <= set_end_date) %>%
  mutate(time = as.numeric(date - set_start_date)) %>%
  select(!date) %>%
  column_to_rownames(var = "time") %>%
  as.matrix()

sero_num_pos_140 

sero_num_pos_020 <- data_seropos_020_wide %>%
  filter(date <= set_end_date) %>%
  mutate(time = as.numeric(date - set_start_date)) %>%
  select(!date) %>%
  column_to_rownames(var = "time") %>%
  as.matrix()

sero_num_pos_020

seroprevalence_times <- data_seropos_140_wide %>%
  filter(date <= set_end_date) %>%
  mutate(time = as.numeric(date - set_start_date)) %>%
  pull(time) 
  
numdays_sero <- length(seroprevalence_times)

numdays_sero  
```
 
### compile input
```{r, data updated}
contactmatrix_unperturbed_normalised <- readRDS("data/contactmatrix_unperturbed_normalised")

# Demography
demography <- pop2020_remapped$total_population

# number of MCMC steps; default = 2000
niter <- 2000
```

## strain frequency
```{r}
phylo_num_sampled <- strain_frequency %>%
  filter(date <= set_end_date) %>%
  mutate(time = as.numeric(date - set_start_date)) %>%
  select(!date) %>%
  column_to_rownames(var = "time") %>%
  pull(number)

phylo_num_pos <- strain_frequency %>%
  filter(date <= set_end_date) %>%
  mutate(time = as.numeric(date - set_start_date)) %>%
  select(!date) %>%
  column_to_rownames(var = "time") %>%
  pull(positive)

phylo_times <- strain_frequency %>%
  filter(date <= set_end_date) %>%
  mutate(time = as.numeric(date - set_start_date)) %>%
  pull(time)

numdays_phylo <- length(phylo_times)
```

## survey
```{r}
data_seropos_survey_start <- data_seropos_survey_start_wide %>%
  filter(date <= set_end_date) %>%
  mutate(time = as.numeric(date - set_start_date)) %>%
  select(!date) %>%
  mutate(across(-time,~ as.numeric(.x - set_start_date))) %>%
  column_to_rownames(var = "time") %>%
  as.matrix() 

data_seropos_survey_start

data_seropos_survey_end <- data_seropos_survey_end_wide %>%
  filter(date <= set_end_date) %>%
  mutate(time = as.numeric(date - set_start_date)) %>%
  select(!date) %>%
  mutate(across(-time,~ as.numeric(.x - set_start_date))) %>%
  column_to_rownames(var = "time") %>%
  as.matrix() 

data_seropos_survey_end


data_stan_Manaus_2w_strainfreq_survey <- list(
  #hosp
  numdays_hospdeaths = numdays_hospdeaths,
  ts_hospdeaths = hospitaldeaths_times$time, 
  hospdeaths = hospitaldeaths_selected,
  #sero
  numdays_sero = numdays_sero,
  ts_sero = seroprevalence_times,
  sero_num_sampled = sero_num_sampled,
  sero_num_pos = sero_num_pos_140, 
  t_sero_start = data_seropos_survey_start,
  t_sero_end = data_seropos_survey_end,
  #other
  numdays_all = numdays_all,
  ts_all = ts_all,
  A = numberofageclasses,
  J = J,
  K = K,
  demography = demography,
  Cunp = contactmatrix_unperturbed_normalised,
  rel_tol = rel_tol,
  abs_tol = abs_tol,
  max_num_steps = max_num_steps,
  t0 = 0,
  t1 = phylogenetic_t1_timepoint_median-30,
  numdays_phylo = numdays_phylo,
  ts_phylo = phylo_times,
  phylo_num_sampled = phylo_num_sampled,
  phylo_num_pos = phylo_num_pos
  )

saveRDS(data_stan_Manaus_2w_strainfreq_survey, file = "job/input/data_stan_Manaus_2w_strainfreq_survey.RDS")
```

```{r}
initial_params <- list(
  beta1 = 0.21, gamma = 0.135, log_inoculum_1 = log(2300), w_raw = 0.8,
  log10_ifr1_intercept = -1.1828, 
  log10_ifr1_slope = 0.524,
  scalar_beta1_re = 0.8, 
  scalar_ifr1_raw = 4,
  delta_ifr = 1,
  beta2 = 0.28, log_inoculum_2 = log(150),
  log10_ifr2_intercept = -0.92, log10_ifr2_slope = 0.31,
  delta_betare = 0.05,
  inv_phi_hosp = 1/20
)

inits_list_2W <- replicate(4, initial_params, simplify = FALSE)

saveRDS(inits_list_2W, file = "job/input/inits_list_2w_strainfreq_survey")
```

#SIRS inits
```{r}
initial_params_SIRS <- list(
  beta1 = 0.21, gamma = 0.135, log_inoculum_1 = log(2300), w_raw = 0.8,
  log10_ifr1_intercept = -1.1828, 
  log10_ifr1_slope = 0.524,
  #scalar_beta1_re = 0.8, 
  #scalar_ifr1_raw = 4,
  #delta_ifr = 1,
  beta2 = 0.28, log_inoculum_2 = log(150),
  log10_ifr2_intercept = -0.92, log10_ifr2_slope = 0.31,
  #delta_betare = 0.05,
  inv_phi_hosp = 1/20
)

inits_list_2W_SIRS <- replicate(4, initial_params, simplify = FALSE)

saveRDS(inits_list_2W_SIRS, file = "job/input/inits_list_2w_strainfreq_survey_SIRS")
```

